modelName = 'Example';
%new_system(modelName);
%open_system(modelName);

% 子函数需要的内容，下面提供了一组管道的信息
rows = 3;
cols = 4;
inletTubes = 1;  % 进口管的序号（进口数目大于一时要求为矩阵格式）
outletTubes = 12; % 出口管的序号（出口数目大于一时要求为矩阵格式）
numInlets = 1;  % 进口数量
numOutlets = 1; % 出口数量
M = [ 0     0     0     1     0     0     0     0     0     0     0     0
     0     0     1     0    -1     0     0     0     0     0     0     0
     0    -1     0     0     0     1     0     0     0     0     0     0
    -1     0     0     0     0     0     1     0     0     0     0     0
     0     1     0     0     0     0     0    -1     0     0     0     0
     0     0    -1     0     0     0     0     0     1     0     0     0
     0     0     0    -1     0     0     0     0     0     1     0     0
     0     0     0     0     1     0     0     0     0     0    -1     0
     0     0     0     0     0    -1     0     0     0     0     0     1
     0     0     0     0     0     0    -1     0     0     0     1     0
     0     0     0     0     0     0     0     1     0    -1     0     0
     0     0     0     0     0     0     0     0    -1     0     0     0];

HX_params = struct(...
       'Cross_sectional_area_A1','pi*(5e-3)^2/4', ...
       'Cross_sectional_area_B1', 'pi*(5e-3)^2/4', ...
       'Cross_sectional_area_A2', '15e-3*4', ...
       'Cross_sectional_area_B2', '15e-3*4', ...
        'Total_length_each_tube', '1', ...
           'Tube_inner_diameter', '5e-3', ...
              'Agg_equiv_length', '0.3', ...
    'Internal_surface_roughness', '15e-6', ...
              'Initial_pressure', '2.5', ...
           'Initial_temperature', '323', ...
           'Length_tube_segment', '1', ...
           'Tube_outer_diameter', '6e-3', ...
       'Longitudinal_tube_pitch', '15e-3', ...
         'Transverse_tube_pitch', '15e-3', ...
            'Fouling_factor_air', '0.1', ...
    'Total_fin_surface_area_air', '0', ...
            'Fin_efficiency_air', '0.5', ...
          'Initial_pressure_air', '0.101325', ...
       'Initial_temperature_air', '293.15', ...
          'Initial_rel_humidity', '0.5');

%%

% 构建管道模块，通用定义

add_block('simulink/Signal Routing/Bus Creator', ...
      modelName + "/" +  'SignalBus');
set_param(modelName + "/SignalBus",'Inputs',num2str(rows*cols*2));
a0 = get_param(modelName + "/" + 'SignalBus',"PortHandles");

handle_Tube = zeros(rows*cols,1); 
handle_Convert1 = zeros(rows*cols,1); 
handle_Convert2 = zeros(rows*cols,1); 

for i = 1 : rows*cols
    fname(i) = "Tube_" + num2str(i);
    fdata1(i) = "Data1_" + num2str(i);
    fdata2(i) = "Data2_" + num2str(i);
    
    handle_Tube(i) = add_block('SimscapeFluids_lib/Heat Exchangers/Two-Phase Fluid - Moist Air/Condenser Evaporator (2P-MA)', ...
         modelName + "/" + fname(i));
    handle_Convert1(i) =  add_block('nesl_utility/PS-Simulink Converter',...
        modelName + "/" + fdata1(i));
    handle_Convert2(i) = add_block('nesl_utility/PS-Simulink Converter',...
        modelName + "/" + fdata2(i));
    
    % 修改添加模块的可重复编译，以减少编译时间
    simscape.reuse.setConfig(modelName + "/" + fname(i),'off')
    %simscape.reuse.setConfig(modelName + "/" + fdata1(i),'on')
    %simscape.reuse.setConfig(modelName + "/" + fdata2(i),'on')


    a = get_param(handle_Tube(i),"PortHandles");
    a1 = get_param(handle_Convert1(i),"PortHandles");
    a2 = get_param(handle_Convert2(i),"PortHandles");

    add_line(modelName,a.LConn(2),a1.LConn(1))
    add_line(modelName,a.RConn(2),a2.LConn(1))

    add_line(modelName,a1.Outport,a0.Inport((i-1)*2 + 1))
    add_line(modelName,a2.Outport,a0.Inport((i-1)*2 + 2))
    
end
%% 进出口的定义与连线
for i = 1:numInlets
    Input_name(i) = "Input_" + num2str(i);
    add_block('simulink/Signal Routing/Connection Port', ...
         modelName + "/" + Input_name(i));
    a = get_param(modelName + "/" + "Tube_" + num2str(inletTubes(i)),"PortHandles");
    b = get_param(modelName + "/" + Input_name(i),"PortHandles");
    add_line(modelName,b.RConn(1),a.LConn(1))
end

for i = 1:numOutlets
    Output_name(i) = "Output_" + num2str(i);
    add_block('simulink/Signal Routing/Connection Port', ...
         modelName + "/" + Output_name(i));
    a = get_param(modelName + "/" +  "Tube_" + num2str(outletTubes(i)),"PortHandles");
    b = get_param(modelName + "/" + Output_name(i),"PortHandles");
    add_line(modelName,b.RConn(1),a.LConn(3))
end

% 给定湿空气的总入口和总出口

add_block('simulink/Signal Routing/Connection Port', ...
         modelName + "/air_Input" );
add_block('simulink/Signal Routing/Connection Port', ...
         modelName + "/air_Output" );

% 连接湿空气总进口和出口
a = get_param(modelName + "/air_Input","PortHandles");
for j = 1:cols
    b = get_param(modelName + "/" + fname(1+(j-1)*3),"PortHandles");
    add_line(modelName,b.RConn(1),a.RConn(1))
end

a = get_param(modelName + "/air_Output","PortHandles");
for j = 1:cols
    b = get_param(modelName + "/" + fname(rows+(j-1)*3),"PortHandles");
    add_line(modelName,b.RConn(3),a.RConn(1))
end

%% 根据连接矩阵进行液体管道的连接
% Two-Phase
for i = 1:rows*cols
    % 遍历管道，获取端口的句柄
    % LConn(1)进口，LConn(3)出口
    a = get_param(modelName + "/" + fname(i),"PortHandles");
    for j = i:rows*cols
        if M(i,j) == 1
            b = get_param(modelName + "/" + fname(j),"PortHandles");
            add_line(modelName,a.LConn(3),b.LConn(1))
        elseif M(i,j) == -1
            b = get_param(modelName + "/" + fname(j),"PortHandles");
            add_line(modelName,b.LConn(3),a.LConn(1))
        end
    end
end

%% 连接湿空气管道
% Moist Air
for i = 1:rows - 1
    % 获取第i排和第i+1排的模块句柄数组
    a1 = i:rows:i+(cols-1)*rows;
    a2 = i+1:rows:i+1+(cols-1)*rows;
    
    for j = 1:cols
        % 连接端口
        a = get_param(modelName + "/" + "Tube_" + num2str(a1(j)),"PortHandles");
        b = get_param(modelName + "/" + "Tube_" + num2str(a2(j)),"PortHandles");
        add_line(modelName,b.RConn(1),a.RConn(3))
    end
    
end


%% 封装

bh = Simulink.findBlocks(modelName);

Mask_name = "HX";

% 创建子系统（新生成的子系统名为 'HX'）
Simulink.BlockDiagram.createSubsystem(bh,'Name',Mask_name);

% 创建封装对象
maskObj = Simulink.Mask.create(modelName + "/" + Mask_name);


%%

maskObj.addParameter('Name', 'Cross_sectional_area_A1', ...
    'Type', 'edit', ...
    'Prompt', 'Cross-sectional area at port A1 (m²):', ...
    'Value', HX_params.Cross_sectional_area_A1);

maskObj.addParameter('Name', 'Cross_sectional_area_B1', ...
    'Type', 'edit', ...
    'Prompt', 'Cross-sectional area at port B1 (m²):', ...
    'Value', HX_params.Cross_sectional_area_B1);

maskObj.addParameter('Name', 'Cross_sectional_area_A2', ...
    'Type', 'edit', ...
    'Prompt', 'Cross-sectional area at port A2 (m²):', ...
    'Value', HX_params.Cross_sectional_area_A2);


maskObj.addParameter('Name', 'Cross_sectional_area_B2', ...
    'Type', 'edit', ...
    'Prompt', 'Cross-sectional area at port B2 (m²):', ...
    'Value', HX_params.Cross_sectional_area_B2);


maskObj.addParameter('Name', 'Total_length_each_tube', ...
    'Type', 'edit', ...
    'Prompt', 'Total length of each tube (m):', ...
    'Value', HX_params.Total_length_each_tube);

maskObj.addParameter('Name', 'Tube_inner_diameter', ...
    'Type', 'edit', ...
    'Prompt', 'Tube inner diameter (m):', ...
    'Value', HX_params.Tube_inner_diameter);

maskObj.addParameter('Name', 'Agg_equiv_length', ...
    'Type', 'edit', ...
    'Prompt', 'Aggregate equivalent length of local resistances (m):', ...
    'Value', HX_params.Agg_equiv_length);

maskObj.addParameter('Name', 'Internal_surface_roughness', ...
    'Type', 'edit', ...
    'Prompt', 'Internal surface absolute roughness (m):', ...
    'Value', HX_params.Internal_surface_roughness);

maskObj.addParameter('Name', 'Initial_pressure', ...
    'Type', 'edit', ...
    'Prompt', 'Initial two-phase fluid pressure (MPa):', ...
    'Value', HX_params.Initial_pressure);

maskObj.addParameter('Name', 'Initial_temperature', ...
    'Type', 'edit', ...
    'Prompt', 'Initial two-phase fluid temperature (K):', ...
    'Value', HX_params.Initial_temperature);

maskObj.addParameter('Name', 'Length_tube_segment', ...
    'Type', 'edit', ...
    'Prompt', 'Length of each tube segment in row (m):', ...
    'Value', HX_params.Length_tube_segment);

maskObj.addParameter('Name', 'Tube_outer_diameter', ...
    'Type', 'edit', ...
    'Prompt', 'Tube outer diameter (m):', ...
    'Value', HX_params.Tube_outer_diameter);

maskObj.addParameter('Name', 'Longitudinal_tube_pitch', ...
    'Type', 'edit', ...
    'Prompt', 'Longitudinal tube pitch (along flow direction) (m):', ...
    'Value', HX_params.Longitudinal_tube_pitch);

maskObj.addParameter('Name', 'Transverse_tube_pitch', ...
    'Type', 'edit', ...
    'Prompt', 'Transverse tube pitch (perpendicular to flow) (m):', ...
    'Value', HX_params.Transverse_tube_pitch);

maskObj.addParameter('Name', 'Fouling_factor_air', ...
    'Type', 'edit', ...
    'Prompt', 'Fouling factor (K*m²/kW):', ...
    'Value', HX_params.Fouling_factor_air);

maskObj.addParameter('Name', 'Total_fin_surface_area_air', ...
    'Type', 'edit', ...
    'Prompt', 'Total fin surface area (m²):', ...
    'Value', HX_params.Total_fin_surface_area_air);

maskObj.addParameter('Name', 'Fin_efficiency_air', ...
    'Type', 'edit', ...
    'Prompt', 'Fin efficiency:', ...
    'Value',  HX_params.Fin_efficiency_air);

maskObj.addParameter('Name', 'Initial_pressure_air', ...
    'Type', 'edit', ...
    'Prompt', 'Initial moist air pressure (MPa):', ...
    'Value',  HX_params.Initial_pressure_air);

maskObj.addParameter('Name', 'Initial_temperature_air', ...
    'Type', 'edit', ...
    'Prompt', 'Initial moist air temperature (K):', ...
    'Value',  HX_params.Initial_temperature_air);

maskObj.addParameter('Name', 'Initial_rel_humidity', ...
    'Type', 'edit', ...
    'Prompt', 'Initial moist air relative humidity:', ...
    'Value',  HX_params.Initial_rel_humidity);

%%

% 参数传递

% 壁面热阻的计算，采用封装内部变量
R = '1000*log(Tube_outer_diameter/Tube_inner_diameter)/(2*pi*Length_tube_segment*380)';
% 计算非总进口和总出口的换热器两端横截面积，同样采用封装内部变量
S = 'pi*Tube_inner_diameter^2/4';

% 内部模块的参数定义不像封装，有可能需要改的全部都需要赋值
for i = 1:rows*cols

    % Configuration
    % 默认叉流和不混合
    set_param(handle_Tube(i), ...
        'flow_arrangement', 'fluids.heat_exchangers.enum.FlowArrangement2PMA.Cross', ...
        'R_wall', R);
    set_param(handle_Tube(i), ...
            'cross_flow_arrangement', 'fluids.heat_exchangers.enum.CrossFlowArrangement2PMA.UnmixedUnmixed');
    

    % 内部液体管道的进出口面积节流信息
    % 如果是总进出口管，对应要将封装的参数输入进来，如果是内部管道，则采用内径计算值
    if any( i == inletTubes )
        set_param(handle_Tube(i), ...
            'area_A1', 'Cross_sectional_area_A1', ...
            'area_B1', S);
    elseif any(i == outletTubes)
        set_param(handle_Tube(i), ...
            'area_A1', S, ...
            'area_B1', 'Cross_sectional_area_B1');
    else
        set_param(handle_Tube(i), ...
            'area_A1', S, ...
            'area_B1', S);
    end
    
    % 由于内部空气侧被列划分开，因此要除以列数
    set_param(handle_Tube(i), ...
        'R_wall', R, ...
        'area_A2', "Cross_sectional_area_A2/" + num2str(cols), ...
        'area_B2', "Cross_sectional_area_B2/" + num2str(cols));

    % 均为默认设置
    %Two-Phase Fluid 1
    set_param(handle_Tube(i), ...
        'tube_cross_section_2P', 'fluids.heat_exchangers.enum.TubeCrossSection.Circular', ...
        'tube_pressure_loss_spec_2P', 'fluids.heat_exchangers.enum.TubePressureLossSpec2P.Haaland', ...
        'tube_local_pressure_loss_spec_2P', 'fluids.heat_exchangers.enum.LocalLossSpec.AggregateLength', ...
        'tube_heat_coeff_spec_2P', 'fluids.heat_exchangers.enum.TubeHeatCoeffSpec2P.GneilinskiCavalliniZecchin', ...
        'energy_spec_2P', 'foundation.enum.energy_spec.temperature');

    set_param(handle_Tube(i), ...
        'tube_num_2P', '1', ...
        'tube_length_2P', 'Total_length_each_tube', ...
        'tube_diameter_2P', 'Tube_inner_diameter', ...
        'tube_length_add_2P', 'Agg_equiv_length', ...
        'tube_roughness_pressure_2P', 'Internal_surface_roughness', ...
        'p_init_2P', 'Initial_pressure', ...
        'T_init_2P', 'Initial_temperature');

    %Moist Air 2
    set_param(handle_Tube(i), ...
        'flow_geometry_MA', 'fluids.heat_exchangers.enum.FlowGeometryMA.AcrossTubeBank', ...
        'bank_pressure_loss_spec_MA', 'fluids.heat_exchangers.enum.BankPressureLossSpec.Martin', ...
        'bank_heat_coeff_spec_MA', 'fluids.heat_exchangers.enum.BankHeatCoeffSpec.Martin', ...
        'humidity_spec_MA', 'foundation.enum.HumiditySpec.RelativeHumidity', ...
        'trace_gas_spec_MA', 'foundation.enum.trace_gas_spec.mass_fraction');
   
    % 默认顺排
    set_param(handle_Tube(i), ...
            'bank_arrangement_MA', 'fluids.heat_exchangers.enum.BankArrangement.Inline');

    set_param(handle_Tube(i), ...
        'bank_num_rows_MA','1', ...
        'bank_tubes_per_row_MA', '1', ...
        'bank_width_MA', 'Length_tube_segment', ...
        'bank_tube_diameter_MA', 'Tube_outer_diameter', ...
        'bank_longitudinal_pitch_MA', 'Longitudinal_tube_pitch', ...
        'bank_transverse_pitch_MA', 'Transverse_tube_pitch', ...
        'fouling_factor_MA', 'Fouling_factor_air', ...
        'fin_area_MA', 'Total_fin_surface_area_air', ...
        'fin_efficiency_MA', 'Fin_efficiency_air', ...
        'p_init_MA', 'Initial_pressure_air', ...
        'T_init_MA', 'Initial_temperature_air', ...
        'RH_init_MA', 'Initial_rel_humidity');    
end