% Generate property module from workspace
% 似乎得做个结构体防止互相干扰，也方便一些
modelName = 'Example';
Maskobj = add_block('fl_lib/Thermal Liquid/Utilities/Thermal Liquid Settings (TL)', ...
      modelName + "/" +  'MyTLProperty');

set_param(Maskobj,...
    'T_TLU','TL_property.T',...
    'p_TLU','TL_property.p',...
    'p_atm','TL_property.p_atm', ...
    'pT_region_flag','foundation.enum.pT_region_TL.validity.matrix',...
    'pT_validity_TLU','TL_property.matrix',...
    'rho_TLU','TL_property.D', ...
    'beta_TLU','TL_property.beta', ...
    'alpha_TLU','TL_property.alpha', ...
    'u_TLU','TL_property.u', ...
    'cp_TLU','TL_property.cp', ...
    'nu_TLU','TL_property.nu', ...
    'k_TLU','TL_property.k');