function [] = Generate_TP_Prop_Module(modelName,moduleName,TP_property)

% Example/
% Generate_TP_Prop_Module('Example','111',ans)

Maskobj = add_block('fl_lib/Two-Phase Fluid/Utilities/Two-Phase Fluid Properties (2P)', ...
      modelName + "/" +  moduleName);

varName = inputname(3);
set_param(Maskobj, ...
    'u_min',            [varName '.u_min'], ...
    'u_max',            [varName '.u_max'], ...
    'p_TLU',            [varName '.p_TLU'], ...          % 原为 'p/1e6'
    'p_crit',           [varName '.p_crit'], ...     % 原为 'p_critcal'
    'critical_region',  'foundation.enum.critical_region.clip', ...
    'p_crit_fraction',  [varName '.p_crit_fraction'], ...
    'p_atm',            [varName '.p_atm'], ...
    'q_rev',            [varName '.q_rev'], ...      % 原为 'p_limit'
    'unorm_liq',        [varName '.unorm_liq'], ...  % 原为 'unorm_liq'
    'v_liq',            [varName '.v_liq'], ...      % 原为 'v_liq'
    's_liq',            [varName '.s_liq'], ...      % 原为 's_liq/1e3'
    'T_liq',            [varName '.T_liq'], ...      % 原为 'T_liq'
    'nu_liq',           [varName '.nu_liq'], ...     % 原为 'nu_liq*1e4'
    'k_liq',            [varName '.k_liq'], ...      % 原为 'k_liq'
    'Pr_liq',           [varName '.Pr_liq'], ...     % 原为 'Pr_liq'
    'u_sat_liq',        [varName '.u_sat_liq'], ...  % 原为 'u_sat_liq/1e3'
    'unorm_vap',        [varName '.unorm_vap'], ...  % 原为 'unorm_vap'
    'v_vap',            [varName '.v_vap'], ...      % 原为 'v_vap'
    's_vap',            [varName '.s_vap'], ...      % 原为 's_vap/1e3'
    'T_vap',            [varName '.T_vap'], ...      % 原为 'T_vap'
    'nu_vap',           [varName '.nu_vap'], ...     % 原为 'nu_vap*1e4'
    'k_vap',            [varName '.k_vap'], ...      % 原为 'k_vap'
    'Pr_vap',           [varName '.Pr_vap'], ...     % 原为 'Pr_vap'
    'u_sat_vap',        [varName '.u_sat_vap']);     % 原为 'u_sat_vap/1e3'


% set_param(Maskobj,...
%     'u_min','u_min',...
%     'u_max','u_max',...
%     'p_TLU','p/1e6', ...
%     'p_crit','p_critcal', ...
%     'critical_region',critical_region, ...
%     'p_crit_fraction','p_crit_fraction', ...
%     'p_atm','p_atm', ...
%     'q_rev','p_limit', ...
%     'unorm_liq','unorm_liq', ...
%     'v_liq','v_liq', ...
%     's_liq','s_liq/1e3', ...
%     'T_liq','T_liq', ...
%     'nu_liq','nu_liq*1e4', ...
%     'k_liq','k_liq', ...
%     'Pr_liq','Pr_liq',...
%     'u_sat_liq','u_sat_liq/1e3',...
%     'unorm_vap','unorm_vap', ...
%     'v_vap','v_vap', ...
%     's_vap','s_vap/1e3', ...
%     'T_vap','T_vap', ...
%     'nu_vap','nu_vap*1e4', ...
%     'k_vap','k_vap', ...
%     'Pr_vap','Pr_vap',...
%     'u_sat_vap','u_sat_vap/1e3');

end