function [] = Generate_TL_Prop_Module(modelName,moduleName,TL_property)
% Generate property module from workspace
% 似乎得做个结构体防止互相干扰，也方便一些
%modelName = 'Example';
Maskobj = add_block('fl_lib/Thermal Liquid/Utilities/Thermal Liquid Settings (TL)', ...
      modelName + "/" +  moduleName);

        varName = inputname(3);
%      set_param(Maskobj,...
%     'T_TLU',[varName '.T'],'TL_property.T',...
%     'p_TLU','TL_property.p',...
%     'p_atm','TL_property.p_atm', ...
%     'pT_region_flag','foundation.enum.pT_region_TL.validity_matrix',...
%     'pT_validity_TLU','TL_property.matrix',...
%     'rho_TLU','TL_property.D', ...
%     'beta_TLU','TL_property.beta', ...
%     'alpha_TLU','TL_property.alpha', ...
%     'u_TLU','TL_property.u', ...
%     'cp_TLU','TL_property.cp', ...
%     'nu_TLU','TL_property.nu', ...
%     'k_TLU','TL_property.k');

set_param(Maskobj,...
    'T_TLU',[varName '.T'],...
    'p_TLU',[varName '.p'],...
    'p_atm',[varName '.p_atm'], ...
    'pT_region_flag','foundation.enum.pT_region_TL.validity_matrix',...
    'pT_validity_TLU',[varName '.matrix'],...
    'rho_TLU',[varName '.D'],...
    'beta_TLU',[varName '.beta'],...
    'alpha_TLU',[varName '.alpha'], ...
    'u_TLU',[varName '.u'],...
    'cp_TLU',[varName '.cp'], ...
    'nu_TLU',[varName '.nu'], ...
    'k_TLU',[varName '.k']);
end