% Generate property module from workspace

modelName = 'Example';
Maskobj = add_block('fl_lib/Two-Phase Fluid/Utilities/Two-Phase Fluid Properties (2P)', ...
      modelName + "/" +  'MyFluidProperty');


set_param(Maskobj,...
    'u_min','u_min',...
    'u_max','u_max',...
    'p_TLU','p/1e6', ...
    'p_crit','p_critcal', ...
    'critical_region',critical_region, ...
    'p_crit_fraction','p_crit_fraction', ...
    'p_atm','p_atm', ...
    'q_rev','p_limit', ...
    'unorm_liq','unorm_liq', ...
    'v_liq','v_liq', ...
    's_liq','s_liq/1e3', ...
    'T_liq','T_liq', ...
    'nu_liq','nu_liq*1e4', ...
    'k_liq','k_liq', ...
    'Pr_liq','Pr_liq',...
    'u_sat_liq','u_sat_liq/1e3',...
    'unorm_vap','unorm_vap', ...
    'v_vap','v_vap', ...
    's_vap','s_vap/1e3', ...
    'T_vap','T_vap', ...
    'nu_vap','nu_vap*1e4', ...
    'k_vap','k_vap', ...
    'Pr_vap','Pr_vap',...
    'u_sat_vap','u_sat_vap/1e3');

