% from Matrix to module
% HeatExchangerWizard
%CoilDesignForUser
% 创建新模型（不打开库浏览器）
modelName = 'HeatExchang';
new_system(modelName);
open_system(modelName);

% 确保 Simscape 库已加载（否则 add_block 会失败）
%load_system('simscape');  % Simscape 基础库

% 子函数需要的内容
rows = str2double(answer{1});
cols = str2double(answer{2});
numInlets = str2double(answer{3});
numOutlets = str2double(answer{4});
M = hxData.matrix;
%%
% 构建管道模块，通用定义
%fname = string(rows*cols,1);
add_block('simulink/Signal Routing/Bus Creator', ...
      modelName + "/" +  'SignalBus');
set_param(modelName + "/SignalBus",'Inputs',num2str(rows*cols*2));
a0 = get_param(modelName + "/" + 'SignalBus',"PortHandles");

handle_Tube = zeros(rows*cols,1); 
handle_Convert1 = zeros(rows*cols,1); 
handle_Convert2 = zeros(rows*cols,1); 

for i = 1 : rows*cols
    fname(i) = "Tube_" + num2str(i);
    fdata1(i) = "Data1_" + num2str(i);
    fdata2(i) = "Data2_" + num2str(i);
    
    handle_Tube(i) = add_block('SimscapeFluids_lib/Heat Exchangers/Two-Phase Fluid - Moist Air/Condenser Evaporator (2P-MA)', ...
         modelName + "/" + fname(i));
    handle_Convert1(i) =  add_block('nesl_utility/PS-Simulink Converter',...
        modelName + "/" + fdata1(i));
    handle_Convert2(i) = add_block('nesl_utility/PS-Simulink Converter',...
        modelName + "/" + fdata2(i));
    
    % 修改添加模块的可重复编译，以减少编译时间
    simscape.reuse.setConfig(modelName + "/" + fname(i),'on')
    %simscape.reuse.setConfig(modelName + "/" + fdata1(i),'on')
    %simscape.reuse.setConfig(modelName + "/" + fdata2(i),'on')


    a = get_param(handle_Tube(i),"PortHandles");
    a1 = get_param(handle_Convert1(i),"PortHandles");
    a2 = get_param(handle_Convert2(i),"PortHandles");

    add_line(modelName,a.LConn(2),a1.LConn(1))
    add_line(modelName,a.RConn(2),a2.LConn(1))

    add_line(modelName,a1.Outport,a0.Inport((i-1)*2 + 1))
    add_line(modelName,a2.Outport,a0.Inport((i-1)*2 + 2))
    
end
%%
% 给定流体的总入口和总出口
for i = 1:numInlets
    Input_name(i) = "Input_" + num2str(i);
    add_block('simulink/Signal Routing/Connection Port', ...
         modelName + "/" + Input_name(i));
    a = get_param(modelName + "/" + "Tube_" + num2str(hxData.inletTubes(i)),"PortHandles");
    b = get_param(modelName + "/" + Input_name(i),"PortHandles");
    add_line(modelName,b.RConn(1),a.LConn(1))
end

for i = 1:numOutlets
    Output_name(i) = "Output_" + num2str(i);
    add_block('simulink/Signal Routing/Connection Port', ...
         modelName + "/" + Output_name(i));
    a = get_param(modelName + "/" +  "Tube_" + num2str(hxData.outletTubes(i)),"PortHandles");
    b = get_param(modelName + "/" + Output_name(i),"PortHandles");
    add_line(modelName,b.RConn(1),a.LConn(3))
end

% 给定湿空气的总入口和总出口

add_block('simulink/Signal Routing/Connection Port', ...
         modelName + "/air_Input" );
add_block('simulink/Signal Routing/Connection Port', ...
         modelName + "/air_Output" );

% 连接湿空气总进口和出口
a = get_param(modelName + "/air_Input","PortHandles");
for j = 1:cols
    b = get_param(modelName + "/" + fname(1+(j-1)*3),"PortHandles");
    add_line(modelName,b.RConn(1),a.RConn(1))
end

a = get_param(modelName + "/air_Output","PortHandles");
for j = 1:cols
    b = get_param(modelName + "/" + fname(rows+(j-1)*3),"PortHandles");
    add_line(modelName,b.RConn(3),a.RConn(1))
end
%% 根据连接矩阵进行液体管道的连接

for i = 1:rows*cols
    % 遍历管道，获取端口的句柄
    % LConn(1)进口，LConn(3)出口
    a = get_param(modelName + "/" + fname(i),"PortHandles");
    for j = i:rows*cols
        if M(i,j) == 1
            b = get_param(modelName + "/" + fname(j),"PortHandles");
            add_line(modelName,a.LConn(3),b.LConn(1))
        elseif M(i,j) == -1
            b = get_param(modelName + "/" + fname(j),"PortHandles");
            add_line(modelName,b.LConn(3),a.LConn(1))
        end
    end
end

%%
% 根据进出口情况，连接空气管道的
for i = 1:rows - 1
    % 获取第i排和第i+1排的模块句柄数组
    a1 = i:rows:i+(cols-1)*rows;
    a2 = i+1:rows:i+1+(cols-1)*rows;
    
    for j = 1:cols
        % 连接端口
        a = get_param(modelName + "/" + "Tube_" + num2str(a1(j)),"PortHandles");
        b = get_param(modelName + "/" + "Tube_" + num2str(a2(j)),"PortHandles");
        add_line(modelName,b.RConn(1),a.RConn(3))
    end
    
end
% 设置好换热器系统的进出口，准备封装

%%

% 模块封装
% 获取模块句柄
bh = Simulink.findBlocks(modelName);

Mask_name = "HX";

% 创建子系统（新生成的子系统名为 'HX'）
Simulink.BlockDiagram.createSubsystem(bh,'Name',Mask_name);

% 创建封装对象
maskObj = Simulink.Mask.create(modelName + "/" + Mask_name);

%%

% 创建封装参数，这些参数用于构建内部管道和风道的信息
Mask_path = modelName +"/" + Mask_name;
HX_handle = num2cell(modelName +"/" + Mask_name + "/" + fname);


%%

% 明确用户侧需要输入的信息

% 模块需要的参数

% 封装参数，以及封装参数和模块参数，用户侧输入参数和模块参数的关系




% ==================== 添加所有参数（无标签页）====================
% Configuration 组

% maskObj.addParameter('Name', 'Wall_thermal_resistance', ...
%     'Type', 'edit', ...
%     'Prompt', 'Wall thermal resistance (K/kW):', ...
%     'Value', HX_params.Wall_thermal_resistance);

% 

maskObj.addParameter('Name', 'Cross_sectional_area_A1', ...
    'Type', 'edit', ...
    'Prompt', 'Cross-sectional area at port A1 (m²):', ...
    'Value', HX_params.Cross_sectional_area_A1);

maskObj.addParameter('Name', 'Cross_sectional_area_B1', ...
    'Type', 'edit', ...
    'Prompt', 'Cross-sectional area at port B1 (m²):', ...
    'Value', HX_params.Cross_sectional_area_B1);

maskObj.addParameter('Name', 'Cross_sectional_area_A2', ...
    'Type', 'edit', ...
    'Prompt', 'Cross-sectional area at port A2 (m²):', ...
    'Value', HX_params.Cross_sectional_area_A2);


maskObj.addParameter('Name', 'Cross_sectional_area_B2', ...
    'Type', 'edit', ...
    'Prompt', 'Cross-sectional area at port B2 (m²):', ...
    'Value', HX_params.Cross_sectional_area_B2);

% Two-Phase Fluid 1 组
% maskObj.addParameter('Name', 'Number_of_tubes', ...
%     'Type', 'edit', ...
%     'Prompt', 'Number of tubes:', ...
%     'Value', '1');

maskObj.addParameter('Name', 'Total_length_each_tube', ...
    'Type', 'edit', ...
    'Prompt', 'Total length of each tube (m):', ...
    'Value', HX_params.Total_length_each_tube);

% maskObj.addParameter('Name', 'Tube_cross_section', ...
%     'Type', 'edit', ...
%     'Prompt', 'Tube cross section:', ...
%     'Value', 'Circular');

maskObj.addParameter('Name', 'Tube_inner_diameter', ...
    'Type', 'edit', ...
    'Prompt', 'Tube inner diameter (m):', ...
    'Value', HX_params.Tube_inner_diameter);

% maskObj.addParameter('Name', 'Pressure_loss_model', ...
%     'Type', 'edit', ...
%     'Prompt', 'Pressure loss model:', ...
%     'Value', 'Correlation for flow inside tubes');
% 
% maskObj.addParameter('Name', 'Local_resistance_spec', ...
%     'Type', 'edit', ...
%     'Prompt', 'Local resistance specification:', ...
%     'Value', 'Aggregate equivalent length');

maskObj.addParameter('Name', 'Agg_equiv_length', ...
    'Type', 'edit', ...
    'Prompt', 'Aggregate equivalent length of local resistances (m):', ...
    'Value', HX_params.Agg_equiv_length);

maskObj.addParameter('Name', 'Internal_surface_roughness', ...
    'Type', 'edit', ...
    'Prompt', 'Internal surface absolute roughness (m):', ...
    'Value', HX_params.Internal_surface_roughness);

% maskObj.addParameter('Name', 'Laminar_Re_upper', ...
%     'Type', 'edit', ...
%     'Prompt', 'Laminar flow upper Reynolds number:', ...
%     'Value', HX_params.Laminar_Re_upper);
% 
% maskObj.addParameter('Name', 'Turbulent_Re_lower', ...
%     'Type', 'edit', ...
%     'Prompt', 'Turbulent flow lower Reynolds number:', ...
%     'Value', HX_params.Turbulent_Re_lower);

% maskObj.addParameter('Name', 'HTC_model', ...
%     'Type', 'edit', ...
%     'Prompt', 'Heat transfer coefficient model:', ...
%     'Value', 'Correlation for flow inside tubes');

% maskObj.addParameter('Name', 'Fouling_factor', ...
%     'Type', 'edit', ...
%     'Prompt', 'Fouling factor (K*m²/kW):', ...
%     'Value', '0.1');
% 
% maskObj.addParameter('Name', 'Total_fin_surface_area', ...
%     'Type', 'edit', ...
%     'Prompt', 'Total fin surface area (m²):', ...
%     'Value', '0');
% 
% maskObj.addParameter('Name', 'Fin_efficiency', ...
%     'Type', 'edit', ...
%     'Prompt', 'Fin efficiency:', ...
%     'Value', '0.5');

% maskObj.addParameter('Name', 'Initial_fluid_energy_spec', ...
%     'Type', 'edit', ...
%     'Prompt', 'Initial fluid energy specification:', ...
%     'Value', '温度');

maskObj.addParameter('Name', 'Initial_pressure', ...
    'Type', 'edit', ...
    'Prompt', 'Initial two-phase fluid pressure (MPa):', ...
    'Value', HX_params.Initial_pressure);

maskObj.addParameter('Name', 'Initial_temperature', ...
    'Type', 'edit', ...
    'Prompt', 'Initial two-phase fluid temperature (K):', ...
    'Value', HX_params.Initial_temperature);

% Moist Air 2 组
% maskObj.addParameter('Name', 'Flow_geometry', ...
%     'Type', 'edit', ...
%     'Prompt', 'Flow geometry:', ...
%     'Value', 'Flow perpendicular to bank of circular tubes');
% 
% maskObj.addParameter('Name', 'Tube_bank_grid_arrangement', ...
%     'Type', 'edit', ...
%     'Prompt', 'Tube bank grid arrangement:', ...
%     'Value', 'Inline');

% maskObj.addParameter('Name', 'Num_tube_rows_along_flow', ...
%     'Type', 'edit', ...
%     'Prompt', 'Number of tube rows along flow direction:', ...
%     'Value', '1');
% 
% maskObj.addParameter('Name', 'Num_tube_segments_per_row', ...
%     'Type', 'edit', ...
%     'Prompt', 'Number of tube segments in each row:', ...
%     'Value', '1');

maskObj.addParameter('Name', 'Length_tube_segment', ...
    'Type', 'edit', ...
    'Prompt', 'Length of each tube segment in row (m):', ...
    'Value', HX_params.Length_tube_segment);

maskObj.addParameter('Name', 'Tube_outer_diameter', ...
    'Type', 'edit', ...
    'Prompt', 'Tube outer diameter (m):', ...
    'Value', HX_params.Tube_outer_diameter);

maskObj.addParameter('Name', 'Longitudinal_tube_pitch', ...
    'Type', 'edit', ...
    'Prompt', 'Longitudinal tube pitch (along flow direction) (m):', ...
    'Value', HX_params.Longitudinal_tube_pitch);

maskObj.addParameter('Name', 'Transverse_tube_pitch', ...
    'Type', 'edit', ...
    'Prompt', 'Transverse tube pitch (perpendicular to flow) (m):', ...
    'Value', HX_params.Transverse_tube_pitch);

% maskObj.addParameter('Name', 'Pressure_loss_model_air', ...
%     'Type', 'edit', ...
%     'Prompt', 'Pressure loss model:', ...
%     'Value', 'Correlation for flow over tube bank');
% 
% maskObj.addParameter('Name', 'HTC_model_air', ...
%     'Type', 'edit', ...
%     'Prompt', 'Heat transfer coefficient model:', ...
%     'Value', 'Correlation for flow over tube bank');

maskObj.addParameter('Name', 'Fouling_factor_air', ...
    'Type', 'edit', ...
    'Prompt', 'Fouling factor (K*m²/kW):', ...
    'Value', HX_params.Fouling_factor_air);

maskObj.addParameter('Name', 'Total_fin_surface_area_air', ...
    'Type', 'edit', ...
    'Prompt', 'Total fin surface area (m²):', ...
    'Value', HX_params.Total_fin_surface_area_air);

maskObj.addParameter('Name', 'Fin_efficiency_air', ...
    'Type', 'edit', ...
    'Prompt', 'Fin efficiency:', ...
    'Value',  HX_params.Fin_efficiency_air);

maskObj.addParameter('Name', 'Initial_pressure_air', ...
    'Type', 'edit', ...
    'Prompt', 'Initial moist air pressure (MPa):', ...
    'Value',  HX_params.Initial_pressure_air);

maskObj.addParameter('Name', 'Initial_temperature_air', ...
    'Type', 'edit', ...
    'Prompt', 'Initial moist air temperature (K):', ...
    'Value',  HX_params.Initial_temperature_air);

% maskObj.addParameter('Name', 'Initial_humidity_spec', ...
%     'Type', 'edit', ...
%     'Prompt', 'Initial humidity specification:', ...
%     'Value', '相对湿度');

maskObj.addParameter('Name', 'Initial_rel_humidity', ...
    'Type', 'edit', ...
    'Prompt', 'Initial moist air relative humidity:', ...
    'Value',  HX_params.Initial_rel_humidity);

% maskObj.addParameter('Name', 'Initial_trace_gas_spec', ...
%     'Type', 'edit', ...
%     'Prompt', 'Initial trace gas specification:', ...
%     'Value', '质量分数');

% maskObj.addParameter('Name', 'Initial_trace_gas_mass_frac', ...
%     'Type', 'edit', ...
%     'Prompt', 'Initial moist air trace gas mass fraction:', ...
%     'Value',  HX_params.Initial_trace_gas_mass_frac);
% 
% maskObj.addParameter('Name', 'Initial_water_droplet_mass_ratio', ...
%     'Type', 'edit', ...
%     'Prompt', 'Initial mass ratio of water droplets to moist air:', ...
%     'Value',  HX_params.Initial_water_droplet_mass_ratio);
% 
% maskObj.addParameter('Name', 'Rel_humidity_saturation', ...
%     'Type', 'edit', ...
%     'Prompt', 'Relative humidity at saturation:', ...
%     'Value', '1');
% 
% maskObj.addParameter('Name', 'Condensation_time_const', ...
%     'Type', 'edit', ...
%     'Prompt', 'Water vapor condensation time constant (s):', ...
%     'Value',  HX_params.Condensation_time_const);
% 
% maskObj.addParameter('Name', 'Evaporation_time_const', ...
%     'Type', 'edit', ...
%     'Prompt', 'Water droplets evaporation time constant (s):', ...
%     'Value',  HX_params.Evaporation_time_const);
% 
% maskObj.addParameter('Name', 'Fraction_condensate_entrained', ...
%     'Type', 'edit', ...
%     'Prompt', 'Fraction of condensate entrained by air:', ...
%     'Value',  HX_params.Fraction_condensate_entrained);

%%


% 除开默认参数外，计算需要计算的参数
% 计算管壁热阻
% 铜管380，铝200
R = '1000*log(Tube_outer_diameter/Tube_inner_diameter)/(2*pi*Length_tube_segment*380)';
% 计算非总进口和总出口的换热器两端横截面积
S = 'pi*Tube_inner_diameter^2/4';


for i = 1:rows*cols

    % 首先根据用户选择，挑选枚举类型
    % Configuration
    set_param(handle_Tube(i), ...
        'flow_arrangement', 'fluids.heat_exchangers.enum.FlowArrangement2PMA.Cross', ...
        'R_wall', R);

    if HX_params.Cross_flow_arrangement == "BothUnmixed"
        set_param(handle_Tube(i), ...
            'cross_flow_arrangement', 'fluids.heat_exchangers.enum.CrossFlowArrangement2PMA.UnmixedUnmixed');
    elseif HX_params.Cross_flow_arrangement == "BothMixed"
        set_param(handle_Tube(i), ...
            'cross_flow_arrangement', 'fluids.heat_exchangers.enum.CrossFlowArrangement2PMA.MixedMixed');
    elseif HX_params.Cross_flow_arrangement == "UnmixedMixed"
        set_param(handle_Tube(i), ...
            'cross_flow_arrangement', 'fluids.heat_exchangers.enum.CrossFlowArrangement2PMA.UnmixedMixed');
    else
        set_param(handle_Tube(i), ...
            'cross_flow_arrangement', 'fluids.heat_exchangers.enum.CrossFlowArrangement2PMA.MixedUnmixed');
    end

     % 内部液体管道的进出口面积节流信息
    if any( i == hxData.inletTubes )
        set_param(handle_Tube(i), ...
            'area_A1', 'Cross_sectional_area_A1', ...
            'area_B1', S);
    elseif any(i == hxData.outletTubes)
        set_param(handle_Tube(i), ...
            'area_A1', S, ...
            'area_B1', 'Cross_sectional_area_B1');
    else
        set_param(handle_Tube(i), ...
            'area_A1', S, ...
            'area_B1', S);
    end
    
    set_param(handle_Tube(i), ...
        'R_wall', R, ...
        'area_A2', "Cross_sectional_area_A2/" + num2str(cols), ...
        'area_B2', "Cross_sectional_area_B2/" + num2str(cols));


    %Two-Phase Fluid 1
    set_param(handle_Tube(i), ...
        'tube_cross_section_2P', 'fluids.heat_exchangers.enum.TubeCrossSection.Circular', ...
        'tube_pressure_loss_spec_2P', 'fluids.heat_exchangers.enum.TubePressureLossSpec2P.Haaland', ...
        'tube_local_pressure_loss_spec_2P', 'fluids.heat_exchangers.enum.LocalLossSpec.AggregateLength', ...
        'tube_heat_coeff_spec_2P', 'fluids.heat_exchangers.enum.TubeHeatCoeffSpec2P.GneilinskiCavalliniZecchin', ...
        'energy_spec_2P', 'foundation.enum.energy_spec.temperature');

    set_param(handle_Tube(i), ...
        'tube_num_2P', '1', ...
        'tube_length_2P', 'Total_length_each_tube', ...
        'tube_diameter_2P', 'Tube_inner_diameter', ...
        'tube_length_add_2P', 'Agg_equiv_length', ...
        'tube_roughness_pressure_2P', 'Internal_surface_roughness', ...
        'p_init_2P', 'Initial_pressure', ...
        'T_init_2P', 'Initial_temperature');

    %Moist Air 2
    set_param(handle_Tube(i), ...
        'flow_geometry_MA', 'fluids.heat_exchangers.enum.FlowGeometryMA.AcrossTubeBank', ...
        'bank_pressure_loss_spec_MA', 'fluids.heat_exchangers.enum.BankPressureLossSpec.Martin', ...
        'bank_heat_coeff_spec_MA', 'fluids.heat_exchangers.enum.BankHeatCoeffSpec.Martin', ...
        'humidity_spec_MA', 'foundation.enum.HumiditySpec.RelativeHumidity', ...
        'trace_gas_spec_MA', 'foundation.enum.trace_gas_spec.mass_fraction');

    if HX_params.Tube_bank_grid_arrangement == "Inline"
        set_param(handle_Tube(i), ...
            'bank_arrangement_MA', 'fluids.heat_exchangers.enum.BankArrangement.Inline');
    else
        set_param(handle_Tube(i), ...
            'bank_arrangement_MA', 'fluids.heat_exchangers.enum.BankArrangement.Staggered');
    end

    set_param(handle_Tube(i), ...
        'bank_num_rows_MA','1', ...
        'bank_tubes_per_row_MA', '1', ...
        'bank_width_MA', 'Length_tube_segment', ...
        'bank_tube_diameter_MA', 'Tube_outer_diameter', ...
        'bank_longitudinal_pitch_MA', 'Longitudinal_tube_pitch', ...
        'bank_transverse_pitch_MA', 'Transverse_tube_pitch', ...
        'fouling_factor_MA', 'Fouling_factor_air', ...
        'fin_area_MA', 'Total_fin_surface_area_air', ...
        'fin_efficiency_MA', 'Fin_efficiency_air', ...
        'p_init_MA', 'Initial_pressure_air', ...
        'T_init_MA', 'Initial_temperature_air', ...
        'RH_init_MA', 'Initial_rel_humidity');    
end